"""add unique to user email - add password hash to users

Revision ID: ac9d3a5c474d
Revises: 8746981be484
Create Date: 2023-09-22 12:05:43.717548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9d3a5c474d'
down_revision = '8746981be484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.create_unique_constraint("unq_email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("unq_email", type_='unique')
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
